### ISSUE TITLE
Update citation in README

### ISSUE THREAD

**Issue by brosaplanella** [pybamm-team/BattBot#52]
Now that the PyBaMM paper has been published, can you update the citation details in the README? (see PyBaMM's updated README).

The formatted citation should read
> Sulzer, V., Marquis, S. G., Timms, R., Robinson, M., & Chapman, S. J. (2021). Python Battery Mathematical Modelling (PyBaMM). _Journal of Open Research Software, 9(1)_.

The Bibtex should read
```
@article{Sulzer2021,
  title = {{Python Battery Mathematical Modelling (PyBaMM)}},
  author = {Sulzer, Valentin and Marquis, Scott G. and Timms, Robert and Robinson, Martin and Chapman, S. Jon},
  doi = {10.5334/jors.309},
  journal = {Journal of Open Research Software},
  publisher = {Software Sustainability Institute},
  volume = {9},
  number = {1},
  pages = {14},
  year = {2021}
}
```

**Comment by Saransh-cpp** [comment]
Yes, on it
