### ISSUE TITLE
Bump up cycle number in Mohtat2020

### ISSUE THREAD

**Issue by tinosulzer** [pybamm-team/BattBot#71]
Let's try bumping up the cycle number in the Mohtat2020 degradation simulations. Ideally getting to 80% capacity (20% drop)

**Comment by Saransh-cpp** [comment]
Should I bump it up to `random.randint(300, 500)`? With `termination` fixed at 80%?

**Comment by tinosulzer** [comment]
Let's do 500 with termination at 80%
