### ISSUE TITLE
Weird legend value when the varied value is 0

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/BattBot#79]
## Tweet
https://twitter.com/battbot_/status/1450368035404009475/photo/1

I think I forgot to add a condition for 0 in #77. The legend should simply show 0.

![image](https://user-images.githubusercontent.com/74055102/138110795-c2842690-875c-4901-9d73-41d8aa06d722.png)

**Comment by Vaibhav-Chopra-GT** [comment]
can i work on this issue
