### ISSUE TITLE
`model_solver` is not being used anywhere

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/BattBot#82]
Remove the function (the whole [folder](https://github.com/pybamm-team/BattBot/tree/main/bot/models) I think) and the tests ([file](https://github.com/pybamm-team/BattBot/blob/main/test/without_keys/test_model_solver.py)), this was initially added to create GIFs with no comparisons.

**Comment by Vaibhav-Chopra-GT** [comment]
I have made a PR for this please check
